config/routes.rb
Rails.application.routes.draw do

  # Setup wizard
  resources :setup

  # Session-management
  get '/login/as/:id' => 'sessions#update', as: 'change_server'
  get '/login/:seed' => 'sessions#temporary', \
    constraints: { seed: /[a-f0-9]{32}/ }, as: 'login_seed'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login/:email' => 'sessions#new', \
    constraints: { email: /[\S]+@[\S]+\.[\S]+/ }

  # Displays the plan-overview as root.
  root 'plans#index'

  # Management of forgot passwords.
  get '/forgot-password' => 'forgot_passwords#new'
  post '/forgot-password' => 'forgot_passwords#create'
  get '/forgot-password/:token' => 'forgot_passwords#edit', \
    constraints: { token: /[a-f0-9]{32}/ }
  post '/forgot-password/save' => 'forgot_passwords#update'

  # Non-administrative user-managment
  get '/register' => 'users#new'
  get '/register/do' => 'users#create'
  get '/settings.bak' => 'users#edit'
  post '/settings.bak' => 'users#update'
  delete '/settings.bak' => 'users#destroy'
  # TODO: Old routes for editing / destroying users are deprecated

  # Interface for user-settings
  get 'settings' => 'settings#servers'
  get 'settings/servers'
  post 'settings/servers' => 'settings#servers_update'
  get 'settings/data'
  post 'settings/data' => 'settings#data_update'
  get 'settings/security'
  get 'settings/security/generate' => 'settings#security_do'
  get 'settings/delete'
  delete 'settings/delete' => 'settings#delete_do'

  # Non-administrative plan-interface.
  resources :plans, only: [ :index, :show, :update ]

  # Administrative REST-API
  namespace :admin do
    resources :servers, except: :show
    resources :users, only: [ :index, :edit, :update, :destroy ]
    resources :plans

    resources :messages
    get '/messages/:id/mail' => 'messages#mail', as: 'message_mail'

    resources :settings, only: :index
    post '/settings' => 'settings#update'
  end

  # API, that currently only displays a calendar. Not sure if more is helpful.
  namespace :api do

    # There is no need for versioning to display a calendar.
    get '/calendars/:api_key' => 'calendars#show', as: 'calendars'
  end

  # Static pages
  get '/about' => 'pages#about'

end

app/controllers/forgot_passwords_controller.rb
# This controller handles request by users, that want to reset their password.
#    This may be the case when the password is forgotten or the user was blocked
#    because of too many failed authentication-attempts.

class ForgotPasswordsController < ApplicationController

  # Allows the user to enter his email-address.
  def new; end

  # Handles the request by email-address and generates an email.
  def create
    email = params[:user][:email]
    @user = User.find_by(email: email)

    if @user.nil?

      # User was not found: Email must be invalid.
      @user = User.new(email: email)
      @user.errors.add(:email, t('.email_not_found'))

    elsif @user.password_reset_expired?

      # There is no ongoing password-resetting-process.
      @user.prepare_password_reset
      UserMailer.forgot_password_mail(@user).deliver_later
      flash.now[:mail_sent] = true
      @user = nil

    else
      flash.now[:reset_link_already_sent] = true
    end

    render :new
  end

  # Allows the user entering a new password by calling this action with a valid
  #    token.
  def edit
    filter_token(params[:token])
  end

  # Actually saves the new password, if everything evaluates as valid.
  def update
    filter_token(params[:user][:password_reset_token]) or return

    if @user.update(params.require(:user).permit(:password, :password_confirmation))
      @user.clear_password_reset
      flash.now[:password_changed] = true
      UserMailer.password_changed_mail(@user).deliver_later
      render 'sessions/new'
    else
      render :edit
    end
  end

  # ============================================================================

  private

  # Assigns the user found by the given token to @user and validates the token.
  #    If the token is invalid (not found in the database) or already expired,
  #    this function returns false, else it returns true.
  def filter_token(token)
    @user = User.find_by(password_reset_token: token)

    if @user.nil?
      flash.now[:invalid_token] = true
      render :new
    elsif @user.password_reset_expired?
      flash.now[:expired_token] = true
      render :new
    else
      return true
    end

    false
  end

end

app/views/forgot_passwords/edit.html.haml
= page_header t('.title'), @user.email
%p.lead= t '.lead'
%p= t '.reset_password_description'

= panel do
  .panel-body

  = simple_horizontal_form_for @user, url: forgot_password_save_path, method: :post do |f|
    = f.hidden_field :password_reset_token
    = f.input :password, autofocus: true
    = f.input :password_confirmation
    .form-group
      .col-sm-offset-3.col-sm-9
        = f.button :submit, t('defaults.submit')
        = btn_link_to t('defaults.cancel'), login_path, context: :link

app/views/forgot_passwords/new.html.haml
= page_header
%p.lead= t '.lead'
%p= t '.reset_password_description'

= flash_messages [:mail_sent, context: :success],
                 [:reset_link_already_sent, context: :warning],
                 [:invalid_token, context: :danger],
                 [:expired_token, context: :warning]

= panel do
  .panel-body

  -# Create a new user if not already specified by a controller.
  - @user ||= User.new
  = simple_horizontal_form_for @user, url: forgot_password_path, method: :post do |f|
    = f.input :email, autofocus: true
    .form-group
      .col-sm-offset-3.col-sm-9
        = f.button :submit, t('defaults.submit')
        = btn_link_to t('defaults.cancel'), login_path, context: :link