config/routes.rb
Rails.application.routes.draw do

  # Setup wizard
  resources :setup

  # Session-management
  get '/login/as/:id' => 'sessions#update', as: 'change_server'
  get '/login/:seed' => 'sessions#temporary', \
    constraints: { seed: /[a-f0-9]{32}/ }, as: 'login_seed'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login/:email' => 'sessions#new', \
    constraints: { email: /[\S]+@[\S]+\.[\S]+/ }

  # Displays the plan-overview as root.
  root 'plans#index'

  # Management of forgot passwords.
  get '/forgot-password' => 'forgot_passwords#new'
  post '/forgot-password' => 'forgot_passwords#create'
  get '/forgot-password/:token' => 'forgot_passwords#edit', \
    constraints: { token: /[a-f0-9]{32}/ }
  post '/forgot-password/save' => 'forgot_passwords#update'

  # Non-administrative user-managment
  get '/register' => 'users#new'
  get '/register/do' => 'users#create'
  get '/settings.bak' => 'users#edit'
  post '/settings.bak' => 'users#update'
  delete '/settings.bak' => 'users#destroy'
  # TODO: Old routes for editing / destroying users are deprecated

  # Interface for user-settings
  get 'settings' => 'settings#servers'
  get 'settings/servers'
  post 'settings/servers' => 'settings#servers_update'
  get 'settings/data'
  post 'settings/data' => 'settings#data_update'
  get 'settings/security'
  get 'settings/security/generate' => 'settings#security_do'
  get 'settings/delete'
  delete 'settings/delete' => 'settings#delete_do'

  # Non-administrative plan-interface.
  resources :plans, only: [ :index, :show, :update ]

  # Administrative REST-API
  namespace :admin do
    resources :servers, except: :show
    resources :users, only: [ :index, :edit, :update, :destroy ]
    resources :plans

    resources :messages
    get '/messages/:id/mail' => 'messages#mail', as: 'message_mail'

    resources :settings, only: :index
    post '/settings' => 'settings#update'
  end

  # API, that currently only displays a calendar. Not sure if more is helpful.
  namespace :api do

    # There is no need for versioning to display a calendar.
    get '/calendars/:api_key' => 'calendars#show', as: 'calendars'
  end

  # Static pages
  get '/about' => 'pages#about'

end

app/models/message.rb
# The messages are send to the servers and stored for later reference.

class Message < ApplicationRecord

  # Each message has an author.
  belongs_to :user
  validates :user, presence: true

  # Subject, text and author must be given. Else the message wouldn't make much
  #    sense, would it?
  validates :subject, :text, presence: true

  # The state indicates, if the message was already sent.
  enum state: [ :draft, :sent ]
  validates :state, presence: true

  # This message is sent to a set number of servers which can be specified by
  #    the sender.
  has_and_belongs_to_many :servers

  # The message can be linked to a plan to send the current plan as pdf.
  belongs_to :plan, required: false

  # ============================================================================

  # Renders the content of the message as html.
  def as_html(server)
    HTMLWithPants.render(parse_text(server)).html_safe
  end

  # Renders the content of the message as plain text.
  def as_text(server)
    Nokogiri::HTML(as_html(server)).text
  end

  # Retrieve a list of servers where duplicated emails (siblings) are removed.
  def to
    servs = servers
    servs.size.times do |i|
      break if i >= servs.size
      servs -= servs[i].siblings
    end
    servs
  end

  # :nodoc:
  def to_s
    subject
  end

  # ============================================================================

  private

  # Replaces keywords in the message with usable substitutes.
  def parse_text(server)
    url = "#{SettingsHelper.get(:domain)}/login/#{server.login_token}"
    text % { firstname: server.firstname, login: url }
  end

end

app/controllers/admin/messages_controller.rb
# Administrative interface for sending messages.

class Admin::MessagesController < Admin::AdminController

  # Gets the selected message for all actions that need exactly one.
  before_action :get_message, except: [ :new, :create, :index ]

  # Already sent emails should not be edited, deleted or sent again: they are
  #    here for documentation pruposes.
  before_action :exclude_sent, only: [ :edit, :update, :destroy, :mail ]

  # ============================================================================

  # Offers a form for creating new messages.
  def new
    @message = Message.new
  end

  # Actually creates the new message.
  def create
    @message = Message.new(message_params)
    @message.update(date: DateTime.now, user: @current_user) and
      return redirect_to admin_message_path(@message)
    render :new
  end

  # Lists all sent and not-sent messages.
  def index
    @messages = Message.order(date: :desc)
  end

  # Shows a single, specific message.
  def show; end

  # Shows a form for editing messages.
  def edit; end

  # Saves updates on the given message.
  def update
    @message.update(message_params) or return render :edit
    @message.update(date: DateTime.now, user: @current_user)
    render :show
  end

  # Destroys a message.
  def destroy
    @message.destroy
    redirect_to admin_messages_path
  end

  # Actually sends a message, which requires quite a few steps.
  def mail

    # Determine all servers which get an email but subtract similar ones, so one
    #    address does not get five emails.
    servers = Server.all
    servers.size.times do |i|
      break if i >= servers.size
      servers -= servers[i].siblings
    end

    # Now sent a message to each server.
    servers.each do |server|
      MessageMailer.global_mail(server, @message).deliver_later
    end

    # Mark the message as sent and display the updated show-enviroment.
    @message.sent!
    render :show
  end

  # ============================================================================

  private

  # Ensures that a message is selected and determines it.
  def get_message
    @message = Message.find_by(id: params[:id])
    @message or redirect_to admin_messages_path
  end

  # Already sent messages are excluded from some actions (see above)
  def exclude_sent
    @message.sent? and return render :show
  end

  # Strong-parameters strong at work.
  def message_params
    params.require(:message).permit(:subject, :text)
  end

end

app/views/admin/messages/_form.html.haml
= simple_horizontal_form_for [ :admin, @message ] do |f|

  = f.input :subject
  = f.input :text

  .form-group
    .col-sm-9.col-sm-offset-3
      = f.button :submit
      = btn_link_to t('defaults.cancel'), action_name == 'edit' ? admin_message_path(@message) : admin_messages_path

app/views/admin/messages/edit.html.haml
= page_header t('.title'), @message
= render 'form'

app/views/admin/messages/index.html.haml
= page_header
%p.lead.clearfix
  = t '.messages', count: @messages.count
  = btn_link_to t('defaults.add'), new_admin_message_path, icon: :plus, context: :success, class: 'pull-right'

- if @messages.any?

  = render 'shared/table_search', id: 'messages-searcher'

  %table.table.table-striped.table-hover.table-rows-link.table-data{ width: '100%', data: { scroll: true, search: '#messages-searcher', column: 2, reverse: true }}
    %thead
      %tr
        %th= Message.human_attribute_name(:subject)
        %th= Message.human_attribute_name(:user)
        %th= Message.human_attribute_name(:date)
        %th= Message.human_attribute_name(:plan)
        %th= Message.human_attribute_name(:state)
    %tbody
      - @messages.each do |message|
        %tr
          %th.text-nowrap= link_to message, admin_message_path(message)
          %td.text-nowrap= message.user
          %td{ data: { order: message.date }}= l message.date
          %td= p = message.plan and link_to p, admin_plan_path(p)
          %td{'data-order' => message[:state]}
            = state_icon(message.state)
            = Message.human_attribute_name("state.#{message.state}")

app/views/admin/messages/new.html.haml
= page_header
= render 'form'

app/views/admin/messages/show.html.haml
= page_header t('.title'), @message

= panel @message.as_html(@current_server), title: t('.html')
= panel title: t('.text') do
  .panel-body
    %pre= @message.as_text(@current_server)

.text-right
  = btn_link_to t('defaults.cancel'), admin_messages_path, icon: :triangle_left
  - if @message.draft?
    = btn_link_to t('defaults.delete'), admin_message_path(@message), method: :delete, context: :danger, icon: :trash, data: { confirm: t('.confirm_delete') }
    = btn_link_to t('defaults.edit'), edit_admin_message_path(@message), icon: :pencil
    = btn_link_to t('defaults.send'), admin_message_mail_path(@message), icon: :send, context: :primary