config/routes.rb
Rails.application.routes.draw do

  # Setup wizard
  resources :setup

  # Session-management
  get '/login/as/:id' => 'sessions#update', as: 'change_server'
  get '/login/:seed' => 'sessions#temporary', \
    constraints: { seed: /[a-f0-9]{32}/ }, as: 'login_seed'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login/:email' => 'sessions#new', \
    constraints: { email: /[\S]+@[\S]+\.[\S]+/ }

  # Displays the plan-overview as root.
  root 'plans#index'

  # Management of forgot passwords.
  get '/forgot-password' => 'forgot_passwords#new'
  post '/forgot-password' => 'forgot_passwords#create'
  get '/forgot-password/:token' => 'forgot_passwords#edit', \
    constraints: { token: /[a-f0-9]{32}/ }
  post '/forgot-password/save' => 'forgot_passwords#update'

  # Non-administrative user-managment
  get '/register' => 'users#new'
  get '/register/do' => 'users#create'
  get '/settings.bak' => 'users#edit'
  post '/settings.bak' => 'users#update'
  delete '/settings.bak' => 'users#destroy'
  # TODO: Old routes for editing / destroying users are deprecated

  # Interface for user-settings
  get 'settings' => 'settings#servers'
  get 'settings/servers'
  post 'settings/servers' => 'settings#servers_update'
  get 'settings/data'
  post 'settings/data' => 'settings#data_update'
  get 'settings/security'
  get 'settings/security/generate' => 'settings#security_do'
  get 'settings/delete'
  delete 'settings/delete' => 'settings#delete_do'

  # Non-administrative plan-interface.
  resources :plans, only: [ :index, :show, :update ]

  # Administrative REST-API
  namespace :admin do
    resources :servers, except: :show
    resources :users, only: [ :index, :edit, :update, :destroy ]
    resources :plans

    resources :messages
    get '/messages/:id/mail' => 'messages#mail', as: 'message_mail'

    resources :settings, only: :index
    post '/settings' => 'settings#update'
  end

  # API, that currently only displays a calendar. Not sure if more is helpful.
  namespace :api do

    # There is no need for versioning to display a calendar.
    get '/calendars/:api_key' => 'calendars#show', as: 'calendars'
  end

  # Static pages
  get '/about' => 'pages#about'

end

app/views/shared/_logo.html.erb
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"
    x="0px" y="0px" width="506px" height="506px" viewBox="0 0 506 506"
    class="tap-logo tap-logo-<%= liturgy[:color] %>"
    data-toggle="popover" data-html="true"
    data-content="<p><%= liturgy[:description] %></p><p><%= t "feasts.colors.#{liturgy[:color]}" %></p>" data-title="<%= liturgy[:title] %>">
  <path class="logo-background" fill="#2D2D2D" d="M500.962,489.713c0,6.627-5.372,12-12,12H15.796c-6.627,0-12-5.373-12-12V16.547
      c0-6.627,5.373-12,12-12h473.166c6.628,0,12,5.373,12,12V489.713z"/>
  <path class="logo-letter" id="T-Path" clip-path="url(#SVGID_2_)" fill="#FFFFFF" d="M229.842,73.848v141.436h153.633v81.692H229.842v318.235
      c0,73.156,20.73,114.608,80.474,114.608c29.265,0,46.334-2.438,62.184-7.314l4.877,81.691
      c-20.729,7.32-53.651,14.633-95.105,14.633c-49.991,0-90.226-17.07-115.831-45.114c-29.264-32.921-41.457-85.351-41.457-154.85
      V296.978H33.536v-81.692h91.447V105.551L229.842,73.848z" />
</svg>

app/views/shared/_menu.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container

    -# Title of the software ("Brand").
    .navbar-header.pull-left
      .navbar-brand= liturgic_logo

    -# Button group for collapsing the menu and changing the current server.
    - if @current_server or @current_user
      .btn-group.pull-right

        -# The css ensures that this button is rounded, if the %button.collapsed below is not shown on large screens.
        - html = @current_server ? [icon(:user), @current_server.firstname].join(' ') : icon(:user)
        = dropdown html, button: { class: 'navbar-btn serverchanger-btn' }, align: :right do
          - if @other_servers.any?
            - @other_servers.each do |other|
              = link_to change_server_path(other.id) do
                = icon :user
                = other.firstname
            %li.divider
          = link_to settings_path do
            = icon :cog
            = t 'defaults.settings'
          = link_to about_path do
            = icon :info_sign
            = t 'defaults.about'
          = link_to logout_path do
            = icon :log_out
            = t 'defaults.logout'

        -# This button allows collapsing of the menubar on smaller screens.
        %button.btn.btn-default.collapsed.navbar-btn.serverchanger-menu{ type: 'button', data: { toggle: 'collapse', target: '#navbar-collapse' }}
          = icon :menu_hamburger

      -# The actual menu is displayed here.
      .collapse.navbar-collapse#navbar-collapse
        %ul.nav.navbar-nav
          - if @current_server
            %li{class: ('active' if controller_name == 'plans' && !@admin)}= link_to Plan.model_name.human(count: :many), plans_path
          - if @current_user.try(:administrator?)
            %li{class: ('active' if @admin)}= link_to t('defaults.administration'), admin_servers_path

app/views/shared/_page_header.html.haml
.page-header
  %h1
    = title.html_safe
    - if remark.present?
      %small= remark
  - unless help_text.empty?
    %button.btn.btn-default.help-btn{ data: { toggle: 'popover', content: help_text }}
      = icon :question_sign

app/views/shared/_register_alert.html.haml
= panel title: t('defaults.register.title'), context: :primary do
  .panel-body
    = simple_format t('defaults.register.body')
    = btn_link_to t('defaults.register.submit'), register_path, context: :primary

app/views/shared/_server_error.html.haml
= alert_box context: :danger do
  :markdown
    #{t('errors.preface') % { time: DateTime.now }}
  %p.lead= t "errors.#{message}"
  %p= t 'errors.postface'

app/views/shared/_server_errors.haml
= alert_box context: :danger do
  :markdown
    #{t('errors.preface') % { time: DateTime.now }}
  - messages.each do |message|
    %p.lead= t "errors.#{message}"
  %p= t 'errors.postface'

app/views/shared/_table_search.html.haml
.row
  .col-md-4.col-md-offset-4.col-sm-6.col-sm-offset-3.search-group
    .input-group
      %span.input-group-addon= icon :search
      %input.form-control{ id: id, type: 'text' }