config/routes.rb
Rails.application.routes.draw do

  # Setup wizard
  resources :setup

  # Session-management
  get '/login/as/:id' => 'sessions#update', as: 'change_server'
  get '/login/:seed' => 'sessions#temporary', \
    constraints: { seed: /[a-f0-9]{32}/ }, as: 'login_seed'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login/:email' => 'sessions#new', \
    constraints: { email: /[\S]+@[\S]+\.[\S]+/ }

  # Displays the plan-overview as root.
  root 'plans#index'

  # Management of forgot passwords.
  get '/forgot-password' => 'forgot_passwords#new'
  post '/forgot-password' => 'forgot_passwords#create'
  get '/forgot-password/:token' => 'forgot_passwords#edit', \
    constraints: { token: /[a-f0-9]{32}/ }
  post '/forgot-password/save' => 'forgot_passwords#update'

  # Non-administrative user-managment
  get '/register' => 'users#new'
  get '/register/do' => 'users#create'
  get '/settings.bak' => 'users#edit'
  post '/settings.bak' => 'users#update'
  delete '/settings.bak' => 'users#destroy'
  # TODO: Old routes for editing / destroying users are deprecated

  # Interface for user-settings
  get 'settings' => 'settings#servers'
  get 'settings/servers'
  post 'settings/servers' => 'settings#servers_update'
  get 'settings/data'
  post 'settings/data' => 'settings#data_update'
  get 'settings/security'
  get 'settings/security/generate' => 'settings#security_do'
  get 'settings/delete'
  delete 'settings/delete' => 'settings#delete_do'

  # Non-administrative plan-interface.
  resources :plans, only: [ :index, :show, :update ]

  # Administrative REST-API
  namespace :admin do
    resources :servers, except: :show
    resources :users, only: [ :index, :edit, :update, :destroy ]
    resources :plans

    resources :messages
    get '/messages/:id/mail' => 'messages#mail', as: 'message_mail'

    resources :settings, only: :index
    post '/settings' => 'settings#update'
  end

  # API, that currently only displays a calendar. Not sure if more is helpful.
  namespace :api do

    # There is no need for versioning to display a calendar.
    get '/calendars/:api_key' => 'calendars#show', as: 'calendars'
  end

  # Static pages
  get '/about' => 'pages#about'

end

app/models/plan.rb
# A plan holds many dates allowing the servers to enroll to them.

class Plan < ApplicationRecord

  # The title is the only way for the user to distinguish plans
  validates :title, presence: true

  # The plan holds multiple events which should be also deleted on destroy
  has_many :events, -> { order(:date) }, dependent: :destroy
  accepts_nested_attributes_for :events, allow_destroy: true

  # Multiple servers can enroll for a plan without really attending to an event.
  #    This allows server to simply say: "I don't have time for **any** event."
  has_and_belongs_to_many :servers

  # ============================================================================

  # Returns the earliest event-date associated to the plan
  def first_date
    events.order(:date).first.date.to_date rescue nil
  end

  # Returns the latest event-date associated to the plan
  def last_date
    events.order(:date).last.date.to_date rescue nil
  end

  # :nodoc:
  def to_s
    title
  end

end

app/controllers/admin/plans_controller.rb
# Administrative plan- and event-managment.

class Admin::PlansController < Admin::AdminController

  # Ensures that a plan is selected for actions that need one.
  before_action :get_plan, only: [ :show, :edit, :update, :destroy ]

  # ============================================================================

  # Shows a form for creating new plans.
  def new
    @plan = Plan.new
  end

  # Actuall creates the new plan
  def create
    @plan = Plan.new(params.require(:plan).permit(:title))

    # First saving and then updating is needed because of a bug, that doesn't
    #    allow saving a model with nested, new created attributes.
    @plan.save
    @plan.update(plan_params) and return redirect_to admin_plan_path(@plan)
    render :new
  end

  # Lists all available plans and sorts them: first those without events, than
  #    the most recents
  def index
    parts = Plan.all.partition { |plan| plan.first_date }
    @plans = parts.last + parts.first.sort_by(&:first_date)
  end

  # Displays a single plan.
  def show; end

  # Allows editing of a single plan.
  def edit; end

  # Actually saves changes to a plan.
  def update
    @plan.update(plan_params) and return redirect_to admin_plan_path(@plan)
    render :edit
  end

  # Destroys a single, given plan.
  def destroy
    @plan.destroy
    redirect_to admin_plans_path
  end

  # ============================================================================

  private

  # Ensures that a plan is selected (and determines it) or aborts the specific
  #    action by redirecting to the overview with available plans.
  def get_plan
    @plan = Plan.find_by(id: params[:id]) or redirect_to admin_plans_path
  end

  # Strong-parameters. Again.
  def plan_params
    params.require(:plan).permit(:title, :remark,
      events_attributes: [ :id, :date, :title, :location, :_destroy, :needed ])
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  # Only servers are allowed to register for the plans
  before_action :require_server

  # Every method that needs a fixed plan provided by an id gets it here.
  before_action :get_plan, only: [ :show, :update ]

  # ============================================================================

  # Displays all plans available to the server, filters out old ones.
  def index
    @plans = Plan.all.find_all{ |p| !p.last_date.past? rescue false } \
      .sort_by(&:first_date)
  end

  # Displays a form to the server where he can enroll for events.
  def show; end

  # Saves the new enrollement of the currently logged in server.
  def update
    params[:events] = [] if params[:events].blank? 
    evts_param = params[:events].map { |id| Event.find_by(id: id) }
    evts_param = evts_param.compact
    events = @current_server.events - @plan.events + evts_param
    flash.now[:enrolled] = @current_server.update(events: events)
    @plan.servers.include?(@current_server) or
      @plan.servers.push(@current_server)
    render :show
  end

  # ============================================================================

  private

  # For every method that needs a fixed plan provided by an id: Get this plan or
  #    redirect to the overview of all plans.
  def get_plan
    @plan = Plan.find_by(id: params[:id]) or redirect_to plans_path
  end

end

app/views/admin/plans/_event_fields.html.haml
%tr.nested-fields
  %td
    = f.input_field :date
    = f.error :date
  %td= f.input_field :title, class: 'form-control'
  %td= f.input_field :location, class: 'form-control'
  %td= f.input_field :needed, class: 'form-control min-control'
  %td
    = link_to_remove_association f, class: 'btn btn-danger' do
      = icon :trash
      = t('defaults.remove')

app/views/admin/plans/_form.html.haml
= simple_horizontal_form_for [ :admin, @plan ] do |f|

  = f.input :title
  = f.input :remark

  %hr/
  %h2= Plan.human_attribute_name(:events)

  .table-responsive
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th= Event.human_attribute_name(:date)
          %th= Event.human_attribute_name(:title)
          %th= Event.human_attribute_name(:location)
          %th= t '.needed'
          %th= t 'defaults.actions'

      %tbody#events-table
        = f.simple_fields_for :events do |event|
          = render 'event_fields', f: event

  .text-right
    = link_to_add_association f, :events, data: { association_insertion_node: '#events-table', association_insertion_method: 'append' }, class: 'btn btn-success' do
      = icon :plus
      = t '.new_event'

  %hr/

  .form-group
    .col-sm-9.col-sm-offset-3
      = f.button :submit
      - if action_name == 'edit'
        = btn_link_to t('defaults.cancel'), admin_plan_path(@plan), context: :link
        = btn_link_to t('defaults.delete'), admin_plan_path(@plan), method: :delete, context: :danger, icon: :trash, data: { confirm: t('.confirm_delete') }
      - else
        = btn_link_to t('defaults.cancel'), admin_plans_path, context: :link

app/views/admin/plans/edit.html.haml
= page_header t('.title'), @plan
= render 'form'

app/views/admin/plans/index.html.haml
= page_header

.table-reponsive
  %table.table.table-striped.table-hover.table-cols-contract
    %thead
      %tr
        %th= Plan.human_attribute_name(:title)
        %th= Plan.human_attribute_name(:events)
        %th.col-expand= Plan.human_attribute_name(:remark)
        %th= btn_link_to t('defaults.add'), new_admin_plan_path, icon: :plus, size: :small, context: :success
    %tbody
      - @plans.each do |plan|
        %tr
          %th= plan
          %td= [ l(plan.first_date), '–', l(plan.last_date) ].join(' ') if plan.first_date
          %td
            - if plan.remark
              :markdown
                #{plan.remark.truncate_words(10)}
          %td= btn_link_to t('defaults.show'), admin_plan_path(plan), icon: :eye_open, size: :small

app/views/admin/plans/show.html.haml
= page_header t('.title'), @plan

:markdown
  #{@plan.remark}

.table-responsive
  %table.table.table-striped.table-hover.table-cols-contract
    %thead
      %tr
        %th{ colspan: 2 }= Event.human_attribute_name(:date)
        %th= Event.human_attribute_name(:location)
        %th= Event.human_attribute_name(:title)
        %th.col-expand= Event.human_attribute_name(:servers)
        %th
    %tbody
      - @plan.events.each do |event|
        %tr
          %td= l event.date.to_date, format: :long
          %td= l event.date, format: :time_only
          %td= event.location
          %th= event.title
          %td
            %small= event.servers.join(', ')
          %td= [ event.enrolled, '/', event.needed ].join(' ')

  .text-right
    = btn_link_to t('defaults.back'), admin_plans_path, icon: :triangle_left
    = btn_link_to t('defaults.edit'), edit_admin_plan_path(@plan), icon: :pencil, context: :primary

app/views/admin/plans/show.pdf.haml
%h3.text-center
  %strong= @plan
  (#{date_range(@plan.first_date, @plan.last_date, format: :long).strip})

%table.table.table-striped.table-condensed.plan-table
  - @plan.events.each do |event|
    %tr
      %th
        = l event.date, format: :plan
        %br/
        %em= event.title
      %th= event.location

      - groups = []
      - event.servers.order(:firstname, :lastname).in_groups_of(10).each { |g| groups << g }
      - (0..9).each do |i|
        %td
          - groups.each do |group|
            = group[i].try(:shortname)
            %br/

:markdown
  #{@plan.remark}